Global:
  epoch_num: 200
  output_dir: ./output/cls_mv3
  batch_size: 64
  image_shape: [3, 224, 224]
  pretrained: 
  label_list: &label_list ['dog','cat']

Architecture:
  Backbone: 
    name: MobileNetV3
    model_name: large
    class_num: 2
  Neck:
  Head:

Loss:
  name: CrossEntropyLoss
  class_num: 2
  label_smooth: 0.1

Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Cosine
    learning_rate: 0.001
    warmup_epoch: 5

PostProcess:
  name: Cls
  topk: 5


Train:
  dataset:
    name: SimpleDataSet
    data_dir: ./train_data/cls/cat_dog
    label_file_list:
      - ./train_data/cls/train_list.txt
    transforms:
      - DecodeImage:
          img_mode: BGR
          channel_first: False
      - ClsLabelEncode: 
          label_list: *label_list # Class handling label
      - BaseDataAugmentation:
      - RandAugment:
      - ClsResizeImg:
          image_shape: [3, 48, 192]
      - KeepKeys:
          keep_keys: ['image', 'label'] # dataloader will return list in this order
  loader:
    shuffle: True
    drop_last: True
    batch_size: 12
    num_workers: 0

Eval:
  dataset:
    name: SimpleDataSet
    data_dir: ./train_data/cls/cat_dog
    label_file_list:
      - ./train_data/cls/val_list.txt
    transforms:
      - DecodeImage: # load image
          img_mode: BGR
          channel_first: False
      - ClsLabelEncode: # Class handling label
          label_list: *label_list 
      - ClsResizeImg:
          image_shape: [3, 48, 192]
      - KeepKeys:
          keep_keys: ['image', 'label'] # dataloader will return list in this order
  loader:
    shuffle: False
    drop_last: False
    batch_size: 12
    num_workers: 0